### ISSUE TITLE
feature request: countdown mode with time

### ISSUE THREAD

**Issue by foldfree** [ethanmdavidson/DeathProgress#1]
The percentage of life already passed by is a bit too abstract (for me, at least)
 A countdown that calculate the time left to live in a format such as:
'years, months, days, hours, minutes, seconds'
Or something in that vein, would be much more potent i believe.
:)

**Comment by ethanmdavidson** [comment]
Thanks for the suggestion! I think this would be a good option to add. I can't promise any particular timeline but I'll work on it when I can.

**Comment by ethanmdavidson** [comment]
The code changes for this have been made, look for an update within the next week (hopefully). Join the beta if you want to get it sooner!
