### ISSUE TITLE
Colors as hex values

### ISSUE THREAD

**Issue by howeyc** [ethanmdavidson/DeathProgress#15]
I have some favorite colors from themes and sports teams for which I know the exact hex values for the color. It would be neat if I could set the colors to those instead of eyeballing it using the wheel.

**Comment by ethanmdavidson** [comment]
Thanks for the feature request. Unfortunately, the [color picker library](https://github.com/skydoves/ColorPickerPreference) I'm using doesn't seem to support this out of the box. I don't think it would be very difficult to build, but I don't have much free time right now so I can't commit to doing it myself. PRs are welcome, of course! (either here or in the color picker library) Or if you can recommend a different color picker that has this functionality.
